### ISSUE TITLE
Cannot resolve module with webpack

### ISSUE THREAD

**Issue by baptadn** [luqin/react-icheck#1]
Hello, thanks for the lib :+1:  

I use it with webpack and it seems that webpack can't find the module react-icheck, I'm stuck with this error when I use the lib `Module not found: Error: Cannot resolve module 'react-icheck'`.

package.json `main` property has the wrong value maybe (`lib/index.js`) ?
https://github.com/luqin/react-icheck/blob/master/package.json#L5

**Comment by luqin** [comment]
@shinework 
Thank you.I will resolve this issue today.

**Comment by baptadn** [comment]
Thank you, it works  :metal:

**Comment by luqin** [comment]
@shinework :smile:
