### ISSUE TITLE
Demo has an issue

### ISSUE THREAD

**Issue by jeffconklin** [luqin/react-icheck#13]
Hello,

Saw your note in the orig iCheck GIT repo about react-icheck and wanted to check this out. Looks very nice.

I wanted to also mention that on the demo page (http://luqin.github.io/react-icheck) I clicked "Radio, #input-4". I then checked "Checkbox, #input-1". Immediately after clicking input-1, the radio button selection on the right also changed to having "Radio, #input-3" checked. Didn't look into why... I just wanted to point it out.

Keep up the good work.

**Comment by luqin** [comment]
Thank you. I plan to dev [react-icheck 1.0](https://github.com/luqin/react-icheck/issues/10)

**Comment by jeffconklin** [comment]
Glad I could help.

When working on the demo, you may want to take a look at the radio buttons throughout the page. For me, in Chrome, they are all acting like checkboxes. Once clicked, they no longer switch properly. A quick screenshot:

![20160115reacticheck](https://cloud.githubusercontent.com/assets/6152325/12359561/fced4d40-bb80-11e5-9d91-4ab21e2f6511.png)

**Comment by luqin** [comment]
Thank for you help. :smile:

**Comment by jeffconklin** [comment]
Just an FYI... the demo still allows you to check multiple radios buttons. It is fine under the "Demo" section, but almost all the other ones allow multiple radios.

![reacticheck](https://cloud.githubusercontent.com/assets/6152325/12409447/14d80e4a-be38-11e5-8d37-a9ea03290146.png)

**Comment by luqin** [comment]
Thank you. I know this issue.
