### ISSUE TITLE
how to change the checkbox size

### ISSUE THREAD

**Issue by tonylinyy** [luqin/react-icheck#19]
thanks for your nice work!
we use the react-icheck in our project
how to change the size of the checkbox,or has the 'size' props?
thanks:)

**Comment by luqin** [comment]
```
// increase clickable area by given % (negative number to decrease)
increaseArea: ''
```

http://icheck.fronteed.com/

**Comment by tonylinyy** [comment]
yes,I try the increaseArea props,but no effect,the size of checkbox no change,here is the code:

> <Checkbox
>                 checkboxClass="icheckbox_square-blue"
>                 increaseArea="-40%"
>                 label="Checkbox, <span class='label1'>#input-1</span>"
>                 checked={this.state.i1checked}
>                 onChange={this.handle1Change}
>               />

**Comment by luqin** [comment]
This plugin base on icheck and support many skin. You can customize the css to get it.
