### ISSUE TITLE
Checkbox generates unknown prop warning in React 15.0.2

### ISSUE THREAD

**Issue by danwarner** [luqin/react-icheck#28]
Upgraded from React 15.0.1 to 15.0.2 and now receive the following dev warnings on react-icheck 0.3.3:

> Warning: Unknown props `checkboxClass`, `increaseArea`, `inputType`, `radioClass`, `checkedClass`, `disabledClass`, `indeterminateClass`, `hoverClass`, `focusClass`, `activeClass`, `labelHover`, `labelHoverClass`, `inheritClass`, `inheritID`, `aria` on <input> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop

**Comment by luqin** [comment]
Welcome your PR. :+1:

**Comment by arnabk** [comment]
👍

**Comment by danwarner** [comment]
@luqin Created a PR!

**Comment by danwarner** [comment]
@luqin you see my PR?

**Comment by salujaharkirat** [comment]
Is anyone working on fixing this issue? Is it fixed or still pending?
